name: deploy-bot-dev

on:
  workflow_run:
    workflows: [infrastructure]
    types:
      - completed

env:
  AZURE_FUNCTIONAPP_NAME: "your-app-name" # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Azure login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: "Resolve Project Dependencies Using Dotnet"
      #   shell: pwsh # For Linux, use bash
      #   run: |
      #     pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      #     dotnet build --configuration Release --output ./output
      #     popd

      # - name: "Run Azure Functions Action"
      #   uses: Azure/functions-action@v1
      #   id: fa
      #   with:
      #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      #     package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
      #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
