name: destroy-ci
workflow_dispatch:
  inputs:
    environment:
      description: "Environment to destroy"
      required: true
      default: "dev"
      type: choice
      options:
        - dev
        - prod

jobs:
  destroy-infrastructure:
    uses: ./.github/workflows/destroy-infrastructure.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
